#  DPFS-License-Identifier: Apache-2.0 license
#  Copyright (C) 2025 LBR.
#  All rights reserved.
#


DPFS_ROOT_DIR := $(abspath $(CURDIR)/../..)

include $(DPFS_ROOT_DIR)/mk/dpfs.common.mk

CXXFLAG += -g

LIB := $(DPFS_ROOT_DIR)/lib/libdpfs_log.so



# OBJS += 

include $(DPFS_ROOT_DIR)/mk/dpfs.lib.mk
